In [2]:
import numpy as np
import pandas as pd

In [ ]:
'''
“Linear Regression from Scratch” - Purpose: the first project where you
build the algorithm, not just the pipeline around it — this is what makes gradient
descent click permanently instead of staying an abstract diagram. - Spec:
numpy only, no scikit-learn. Generate or download a small single-feature or
two-feature dataset (e.g., a simple synthetic linear relationship with noise, or a
small real dataset like height-vs-weight). - Deliverables: implement the cost
function (MSE), the gradient computation, and the update loop by hand; plot
the cost decreasing over iterations to confirm convergence; plot your fitted line
against the data; compare your learned coefficients against np.linalg.lstsq
or scikit-learn’s LinearRegression on the same data and report how close they
are. - Stretch goal: implement logistic regression from scratch the same way
(sigmoid + binary cross-entropy loss instead of MSE) on a small 2-class synthetic
dataset — this directly previews Project 1’s core model family.
'''

In [4]:
df = pd.read_csv('SOCR-HeightWeight.csv')
df.head()

,Height(Inches),Weight(Pounds)
0,65.78331,112.9925
1,71.51521,136.4873
2,69.39874,153.0269
3,68.21660,142.3354
4,67.78781,144.2971


In [5]:
x_array = df['Height(Inches)'].to_numpy()
x_array

array([65.78331, 71.51521, 69.39874, 68.2166 , 67.78781, 68.69784,
       69.80204, 70.01472, 67.90265, 66.78236, 66.48769, 67.62333,
       68.30248, 67.11656, 68.27967, 71.0916 , 66.461  , 68.64927,
       71.23033, 67.13118, 67.83379, 68.87881, 63.48115, 68.42187,
       67.62804, 67.20864, 70.84235, 67.49434, 66.53401, 65.44098,
       69.5233 , 65.8132 , 67.8163 , 70.59505, 71.80484, 69.20613,
       66.80368, 67.65893, 67.80701, 64.04535, 68.57463, 65.18357,
       69.65814, 67.96731, 65.98088, 68.67249, 66.88088, 67.69868,
       69.82117, 69.08817])

In [6]:
y_array = df['Weight(Pounds)'].to_numpy()
y_array

array([112.9925 , 136.4873 , 153.0269 , 142.3354 , 144.2971 , 123.3024 ,
       141.4947 , 136.4623 , 112.3723 , 120.6672 , 127.4516 , 114.143  ,
       125.6107 , 122.4618 , 116.0866 , 139.9975 , 129.5023 , 142.9733 ,
       137.9025 , 124.0449 , 141.2807 , 143.5392 ,  97.90191, 129.5027 ,
       141.8501 , 129.7244 , 142.4235 , 131.5502 , 108.3324 , 113.8922 ,
       103.3016 , 120.7536 , 125.7886 , 136.2225 , 140.1015 , 128.7487 ,
       141.7994 , 121.2319 , 131.3478 , 106.7115 , 124.3598 , 124.8591 ,
       139.6711 , 137.3696 , 106.4499 , 128.7639 , 145.6837 , 116.819  ,
       143.6215 , 134.9325 ])

In [7]:
def compute_cost(x, y, w, b):
    m = x.shape[0]
    cost_sum = 0
    for i in range(m):
        f_wb = w * x[i] + b
        cost = (f_wb - y[i]) ** 2
        cost_sum = cost_sum + cost
    total_cost = (1/(2*m)) * cost_sum
    return total_cost

In [8]:
compute_cost(x_array, y_array, 0.0, 0.0)

np.float64(8381.646705462179)

In [9]:
def z_score_normalization(x):
    mu = np.mean(x)
    sigma = np.std(x)
    x_norm = (x-mu)/sigma

    return x_norm


In [11]:
x_scaled = z_score_normalization(x_array)
x_scaled

array([-1.25697409,  1.91773552,  0.74549287,  0.09074466, -0.14674792,
        0.35728756,  0.96886738,  1.08666379, -0.08314184, -0.70363338,
       -0.86684133, -0.23784794,  0.13831075, -0.51853107,  0.12567705,
        1.68311196, -0.88162404,  0.33038625,  1.75994992, -0.51043353,
       -0.12128112,  0.45752086, -2.53206428,  0.20443692, -0.23523923,
       -0.467531  ,  1.54506064, -0.30929123, -0.84118622, -1.44657934,
        0.81448253, -1.24041901, -0.13096825,  1.40808936,  2.07815198,
        0.63881256, -0.69182494, -0.21813028, -0.13611367, -2.21957259,
        0.28904563, -1.58915022,  0.88916594, -0.04732881, -1.14754661,
        0.34324704, -0.64906641, -0.19611407,  0.97946285,  0.57347843])

In [12]:
compute_cost(x_scaled, y_array, 0.0, 0.0)

np.float64(8381.646705462179)

In [16]:
def compute_gradient(x, y, w, b): 
  
    m = x.shape[0]    
    dj_dw = 0
    dj_db = 0
    
    for i in range(m):  
        f_wb = w * x[i] + b 
        dj_dw_i = (f_wb - y[i]) * x[i] 
        dj_db_i = f_wb - y[i] 
        dj_db += dj_db_i
        dj_dw += dj_dw_i 
    dj_dw = dj_dw / m 
    dj_db = dj_db / m 
        
    return dj_dw, dj_db

In [23]:
def gradient_descent(x, y, w_in, b_in, alpha, num_iters, cost_function, gradient_function):
    j_history = []
    p_history = []
    b = b_in
    w = w_in       
    
    b = b - alpha * dj_db 
    W = w - alpha * dj_dw

    for i in range(num_iters):
        dj_dw, dj_db = gradient_function(x, y, w , b)     
        b = b - alpha * dj_db 
        w = w - alpha * dj_dw

        if i < 100000:
            j_history.append(cost_function(x,y,w,b))
            p_history.append([w,b])
        if i% math.ceil(num_iters/10) == 0:
            print(f"Iteration {i:4}: Cost {J_history[-1]:0.2e} ",
                  f"dj_dw: {dj_dw: 0.3e}, dj_db: {dj_db: 0.3e}  ",
                  f"w: {w: 0.3e}, b:{b: 0.5e}")

    return w, b, j_history, p_history